### ISSUE TITLE
Feature request: 

### ISSUE THREAD

**Issue by kephale** [morphonets/SNT#174] opened 2023-06-05 23:41 UTC
**Is your feature request related to a problem? Please describe.**

Some IJ2 Commands in SNT cannot be discovered in napari-imagej, like SkeletonizerCmd. Ran into this here https://github.com/imagej/napari-imagej/issues/262

**Describe the solution you'd like**

Can the Commands in `sc.fiji.snt.plugin` be changed to have `visible = true`?

**Describe alternatives you've considered**

Unclear what the alternatives would be.

**Additional context**

Trying to expose SNT through napari-imagej

**Comment by tferr** [comment] 2023-06-11 12:23
with `visible = true` they appear in the Quick Search... results (that search bar in Fiji, written by Curtis et al).  It is silly to have the commands listed because they are not registered in the ImageJ UI, and pressing _Run_ on a searched SNT command is a guaranteed failure since the inputs won't be properly defined. 

But Napari support is way more important! so I tried to make the bulk of them visible with 9ad2b61 (I think I toggled the visibility of most commands, but do let me know if I have missed some).

Any problems caused by search results in Fiji can be tracked here: https://github.com/scijava/scijava-search/issues/31

**Comment by tferr** [comment] 2023-06-11 13:25
v4.1.20 has been released with this change! (BTW: In this version core classes no longer rely on LegacyService: I kept running (initialization errors) into issues with pyimagej related to LegacyService. Now that it is not needed, those are gone :smile: )

Closing this issue for now. We can always open it if something is needed

**Closed by tferr** 2023-06-11 13:25 UTC
Labels: enhancement
